BASE_URL = "https://www.instagram.com/"
URL_LIKES = "https://www.instagram.com/web/likes/%s/like/"
URL_LOGIN = BASE_URL + "accounts/login/ajax/"
URL_LOGOUT = "https://www.instagram.com/accounts/logout/"
URL_MEDIA_DETAIL = "https://www.instagram.com/p/%s/?__a=1"
